### ISSUE TITLE
Running the contributed command:'extension.jscpd' failed.

### ISSUE THREAD

**Issue by miroslaw-dubaj** [paulhoughton/vscode-jscpd#7]
Extension version is 0.3.4
VSC version is 1.26.1
jscpd version is 0.6.22

Error from Dev Tools:
`Error: Running the contributed command:'extension.jscpd' failed.
	at e._executeContributedCommand (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:87)
	at e.$executeContributedCommand (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:479)
	at e._doInvokeHandler (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:983)
	at e._invokeHandler (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:701)
	at e._receiveRequest (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:767)
	at e._receiveOneMessage (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:536)
	at c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:669:452
	at c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:672:575
	at c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:903
	at e.fire (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
	at a (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:713)
	at Socket._socketDataListener (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
t.onDidNotificationChange @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2386
(anonymous) @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2385
e.fire @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:172
t.notify @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2379
t.error @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3457
t.onError @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2941
(anonymous) @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2941
done @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:157
v @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:152
enter @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155
_run @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156
_error @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156
e.resolveErr @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3136
e._receiveReplyErr @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3204
e._receiveOneMessage @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3203
(anonymous) @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3202
(anonymous) @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3205
e.fire @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:172
a @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:307
n._socketDataListener @ /C:/Users/mdubaj/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:307
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594`

Any ideas?

**Comment by paulhoughton** [comment]
Any more detail under Output -> Log (Extension Host) ?

When is this triggered? When running from command palette? Any difference if you run via right clicking on a directory in the explorer pane?

**Comment by miroslaw-dubaj** [comment]
It triggers from command palette. Via right clicking nothing is shown, but OUTPUT Log (Extension Host) shows this in both cases: 

`[2018-09-06 10:11:51.587] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\mdubaj\.vscode\extensions\shinnn.stylelint-0.42.0\index.js
[2018-09-06 10:13:05.650] [exthost1] [info] ExtensionService#_doActivateExtension paulhoughton.vscode-jscpd {"startup":false,"activationEvent":"onCommand:extension.jscpd"}
[2018-09-06 10:13:05.650] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\mdubaj\.vscode\extensions\paulhoughton.vscode-jscpd-0.3.4\src\extension
[2018-09-06 10:13:07.244] [exthost1] [error] TypeError: Cannot read property 'split' of undefined
	at C:\Users\mdubaj\.vscode\extensions\paulhoughton.vscode-jscpd-0.3.4\node_modules\jscpd\lib\preprocessors\options.js:64:40
	at Array.forEach (<anonymous>)
	at parseLanguagesExtensions (C:\Users\mdubaj\.vscode\extensions\paulhoughton.vscode-jscpd-0.3.4\node_modules\jscpd\lib\preprocessors\options.js:61:27)
	at prepareOptions (C:\Users\mdubaj\.vscode\extensions\paulhoughton.vscode-jscpd-0.3.4\node_modules\jscpd\lib\preprocessors\options.js:27:40)
	at optionsPreprocessor (C:\Users\mdubaj\.vscode\extensions\paulhoughton.vscode-jscpd-0.3.4\node_modules\jscpd\lib\preprocessors\options.js:80:15)
	at JsCpd.execPreProcessors (C:\Users\mdubaj\.vscode\extensions\paulhoughton.vscode-jscpd-0.3.4\node_modules\jscpd\lib\jscpd.js:28:11)
	at JsCpd.run (C:\Users\mdubaj\.vscode\extensions\paulhoughton.vscode-jscpd-0.3.4\node_modules\jscpd\lib\jscpd.js:36:14)
	at C:\Users\mdubaj\.vscode\extensions\paulhoughton.vscode-jscpd-0.3.4\src\extension.js:68:31
	at e._executeContributedCommand (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:712:994)
	at e.$executeContributedCommand (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:479)
	at e._doInvokeHandler (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:983)
	at e._invokeHandler (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:701)
	at e._receiveRequest (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:767)
	at e._receiveOneMessage (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:536)
	at c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:669:452
	at c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:672:575
	at c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:903
	at e.fire (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
	at a (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:713)
	at Socket._socketDataListener (c:\Users\mdubaj\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) extension.jscpd
`

**Comment by paulhoughton** [comment]
What do you have for jscpd.languageExts in settings? It's failing to process it.

Will look to improve the error messages to help with issues like this.

**Comment by miroslaw-dubaj** [comment]
THANKS A LOT!
I had  "jscpd.languagesExts": "sass:scss;"
I have hanged it to "jscpd.languagesExts": "scss:scss;javascript:es5,es6,es7,js;php:php5;vue.js:vue" and it works with command palette.
It also seems to be working on right clicking folders, but... in this case it shows 0 duplicated lines. 
Maybe im using it wrong as I have read in other issues, that there was some kind of problem with this feature.
